### ISSUE TITLE
Добавить команду create_ticket

### ISSUE THREAD

**Issue by lwof** [AndreyGolovin85/Flask_Dp_TelegramHelpDesk#2]
Когда пользователь присылает `/create_ticket my computer doesn't work`, мы хотим чтобы текст этого тикета появился в списке тикетов. 
Если прислали просто команду `/create_ticket` обработать этот случай, и прислать в ответ пример использования. 

Класть в тикет айди пользователя создателя.

**Comment by SoraAki000** [comment]
Команду сделал, но не `create_ticket`, а `new_ticket`
